export const defaultList = [
    {
        id: '1',
        firstName: 'John',
        lastName: 'Doe',
        name: 'John Doe',
        role: 'Developer',
        company: 'ABC',
    },
    {
        id: '2',
        firstName: 'Jane',
        lastName: 'Doe',
        name: 'Jane Doe',
        role: 'Developer',
        company: 'ABC',
    },
    {
        id: '3',
        firstName: 'Fred',
        lastName: 'Smith',
        name: 'Fred Smith',
        role: 'Product Manager',
        company: 'Hazy',
    },
    {
        id: '4',
        firstName: 'Jane',
        lastName: 'Smith',
        name: 'Jane Smith',
        role: 'Product Owner',
        company: 'BBC',
    },
    {
        id: '5',
        firstName: 'John',
        lastName: 'Smith',
        name: 'John Smith',
        role: 'Tester',
        company: 'ITV',
    },
    {
        id: '6',
        firstName: 'Fred',
        lastName: 'Jones',
        name: 'Fred Jones',
        role: 'Top person who does everything that you can think of',
        company: 'The company with a really long name',
    },
    {
        id: '7',
        firstName: 'Jane',
        lastName: 'Jones',
        name: 'Jane Jones', 
        role: 'Developer',
        company: 'ABC',
    },
    {
        id: '8',
        firstName: 'John',
        lastName: 'Brown',
        name: 'John Brown',
        role: 'Business Analyst',
        company: 'ZetX',
    },
    {
        id: '9',
        firstName: 'Kate',
        lastName: 'Taylor',
        name: 'Kate Taylor',
        role: 'Developer',
        company: 'SAE',
    },
    {
        id: '10',
        firstName: 'David',
        lastName: 'Johnson',
        name: 'David Johnson',
        role: 'Product Manager',
        company: 'VinCo',
    },
    {
        id: '11',
        firstName: 'Mark',
        lastName: 'Williams',
        name: 'Mark Williams',
        role: 'Engineer',
        company: 'FoloTech',
    },
    {
        id: '12',
        firstName: 'Linda',
        lastName: 'Jones',
        name: 'Linda Jones',
        role: 'Data Scientist',
        company: 'Neo',
    },
    {
        id: '13',
        firstName: 'Bob',
        lastName: 'Brown',
        name: 'Bob Brown',
        role: 'Software Architect',
        company: 'StarNet',
    },
    {
        id: '14',
        firstName: 'Steve',
        lastName: 'Smith',
        name: 'Steve Smith',
        role: 'QA Engineer',
        company: 'Tide',
    },
    {
        id: '15',
        firstName: 'Carol',
        lastName: 'Taylor',
        name: 'Carol Taylor',
        role: 'Business Analyst',
        company: 'IMA',
    },
    {
        id: '16',
        firstName: 'Paul',
        lastName: 'Miller',
        name: 'Paul Miller',
        role: 'Developer',
        company: 'Volo',
    },
    {
        id: '17',
        firstName: 'Helen',
        lastName: 'Doe',
        name: 'Helen Doe',
        role: 'Product Manager',
        company: 'PTA',
    },
    {
        id: '18',
        firstName: 'Richard',
        lastName: 'Johnson',
        name: 'Richard Johnson',
        role: 'Engineer',
        company: 'Xeno',
    },
    {
        id: '19',
        firstName: 'Susan',
        lastName: 'Williams',
        name: 'Susan Williams',
        role: 'Data Scientist',
        company: 'United',
    },
    {
        id: '20',
        firstName: 'Tim',
        lastName: 'Jones',
        name: 'Tim Jones',
        role: 'Software Architect',
        company: 'Hedon',
    },
    {
        id: '21',
        firstName: 'Joseph',
        lastName: 'Brown',
        name: 'Joseph Brown',
        role: 'QA Engineer',
        company: 'GreenTech',
    },
    {
        id: '22',
        firstName: 'Deborah',
        lastName: 'Taylor',
        name: 'Deborah Taylor',
        role: 'Business Analyst',
        company: 'EarlX',
    },
    {
        id: '23',
        firstName: 'Dan',
        lastName: 'Miller',
        name: 'Dan Miller',
        role: 'Developer',
        company: 'ICT',
    },
    {
        id: '24',
        firstName: 'Stephanie',
        lastName: 'Doe',
        name: 'Stephanie Doe',
        role: 'Product Manager',
        company: 'Yancey',
    },
    {
        id: '25',
        firstName: 'Gary',
        lastName: 'Johnson',
        name: 'Gary Johnson',
        role: 'Engineer',
        company: 'Glandos',
    },
    {
        id: '26',
        firstName: 'Laura',
        lastName: 'Williams',
        name: 'Laura Williams',
        role: 'Data Scientist',
        company: 'StarNet',
    },
    {
        id: '27',
        firstName: 'Kelly',
        lastName: 'Jones',
        name: 'Kelly Jones',
        role: 'Software Architect',
        company: 'Carisel',
    },
    {
        id: '28',
        firstName: 'Patrick',
        lastName: 'Brown',
        name: 'Patrick Brown',
        role: 'QA Engineer',
        company: 'Foxy',
    },
    {
        id: '29',
        firstName: 'Nancy',
        lastName: 'Taylor',
        name: 'Nancy Taylor',
        role: 'Business Analyst',
        company: 'Karmic',
    },
    {
        id: '30',
        firstName: 'George',
        lastName: 'Miller',
        name: 'George Miller',
        role: 'Developer',
        company: 'Lilac',
    },
    {
        id: '31',
        firstName: 'Amy',
        lastName: 'Doe',
        name: 'Amy Doe',
        role: 'Product Manager',
        company: 'VonCo',
    },
    {
        id: '32',
        firstName: 'Brian',
        lastName: 'Johnson',
        name: 'Brian Johnson',
        role: 'Engineer',
        company: 'SkyLark',
    },
    {
        id: '33',
        firstName: 'Catherine',
        lastName: 'Williams',
        name: 'Catherine Williams',
        role: 'Data Scientist',
        company: 'VinNet',
    },
    {
        id: '34',
        firstName: 'John',
        lastName: 'Jones',
        name: 'John Jones',
        role: 'Software Architect',
        company: 'MobiTech',
    },
    {
        id: '35',
        firstName: 'Scott',
        lastName: 'Brown',
        name: 'Scott Brown',
        role: 'QA Engineer',
        company: 'LitHop',
    },
    {
        id: '36',
        firstName: 'Robin',
        lastName: 'Taylor',
        name: 'Robin Taylor',
        role: 'Business Analyst',
        company: 'Hiso',
    },
    {
        id: '37',
        firstName: 'Carl',
        lastName: 'Miller',
        name: 'Carl Miller',
        role: 'Developer',
        company: 'Ooma',
    },
    {
        id: '38',
        firstName: 'Will',
        lastName: 'Doe',
        name: 'Will Doe',
        role: 'Product Manager',
        company: 'Link',
    },
    {
        id: '39',
        firstName: 'Pamela',
        lastName: 'Johnson',
        name: 'Pamela Johnson',
        role: 'Engineer',
        company: 'GiftTech',
    },
    {
        id: '40',
        firstName: 'Paula',
        lastName: 'Williams',
        name: 'Paula Williams',
        role: 'Data Scientist',
        company: 'Omega',
    },
    {
        id: '41',
        firstName: 'Diana',
        lastName: 'Jones',
        name: 'Diana Jones',
        role: 'Software Architect',
        company: 'Flexon',
    },
    {
        id: '42',
        firstName: 'Steve',
        lastName: 'Brown',
        name: 'Steve Brown',
        role: 'QA Engineer',
        company: 'ARealm',
    },
    {
        id: '43',
        firstName: 'Rebecca',
        lastName: 'Taylor',
        name: 'Rebecca Taylor',
        role: 'Business Analyst',
        company: 'GeoVax',
    },
    {
        id: '44',
        firstName: 'Andrew',
        lastName: 'Miller',
        name: 'Andrew Miller',
        role: 'Developer',
        company: 'Gurksy',
    },
    {
        id: '45',
        firstName: 'Margaret',
        lastName: 'Doe',
        name: 'Margaret Doe',
        role: 'Product Manager',
        company: 'Economia',
    },
    {
        id: '46',
        firstName: 'Craig',
        lastName: 'Johnson',
        name: 'Craig Johnson',
        role: 'Engineer',
        company: 'Kloude',
    },
    {
        id: '47',
        firstName: 'Kathy',
        lastName: 'Williams',
        name: 'Kathy Williams',
        role: 'Data Scientist',
        company: 'Zenith',
    },
    {
        id: '48',
        firstName: 'Ralph',
        lastName: 'Jones',
        name: 'Ralph Jones',
        role: 'Software Architect',
        company: 'Poke',
    },
    {
        id: '49',
        firstName: 'Lori',
        lastName: 'Brown',
        name: 'Lori Brown',
        role: 'QA Engineer',
        company: 'Utopia',
    },
    {
        id: '50',
        firstName: 'John',
        lastName: 'Taylor',
        name: 'John Taylor',
        role: 'Business Analyst',
        company: 'Eon',
    },
    {
        id: '51',
        firstName: 'Anonymous',
        lastName: 'Lee',
        name: 'Anonymous Lee',
        role: 'Product Manager',
        company: 'Britz',
    },
    {
        id: '52',
        firstName: 'Lee',
        lastName: 'Thompson',
        name: 'Lee Thompson',
        role: 'Software Engineer',
        company: 'Enigma',
    },
    {
        id: '53',
        firstName: 'Amy',
        lastName: 'Cooper',
        name: 'Amy Cooper',
        role: 'Accountant',
        company: 'Hyperion',
    },
    {
        id: '54',
        firstName: 'Mabel',
        lastName: 'Carr',
        name: 'Mabel Carr',
        role: 'Network Engineer',
        company: 'Origin',
    },
    {
        id: '55',
        firstName: 'James',
        lastName: 'Nguyen',
        name: 'James Nguyen',
        role: 'Data Scientist',
        company: 'Magma',
    },
    {
        id: '56',
        firstName: 'Ricardo',
        lastName: 'Gomez',
        name: 'Ricardo Gomez',
        role: 'Software Developer',
        company: 'Dino',
    },
    {
        id: '57',
        firstName: 'Denise',
        lastName: 'Hunter',
        name: 'Denise Hunter',
        role: 'HR Manager',
        company: 'Oyster',
    },
    {
        id: '58',
        firstName: 'Beverly',
        lastName: 'Richards',
        name: 'Beverly Richards',
        role: 'Content Designer',
        company: 'Velvet',
    },
    {
        id: '59',
        firstName: 'Lorraine',
        lastName: 'Terry',
        name: 'Lorraine Terry',
        role: 'Support Engineer',
        company: 'Atomic',
    },
    {
        id: '60',
        firstName: 'Seth',
        lastName: 'Morgan',
        name: 'Seth Morgan',
        role: 'Frontend Developer',
        company: 'Vortex',
    },
    {
        id: '61',
        firstName: 'Anna',
        lastName: 'Robinson',
        name: 'Anna Robinson',
        role: 'UI Designer',
        company: 'Volta',
    },
    {
        id: '62',
        firstName: 'Carlos',
        lastName: 'Sanchez',
        name: 'Carlos Sanchez',
        role: 'DevOps Engineer',
        company: 'Tera',
    },
    {
        id: '63',
        firstName: 'Kathleen',
        lastName: 'Morrison',
        name: 'Kathleen Morrison',
        role: 'Business Analyst',
        company: 'Interactive',
    },
    {
        id: '64',
        firstName: 'Harold',
        lastName: 'Myers',
        name: 'Harold Myers',
        role: 'Scrum Master',
        company: 'Dynamite',
    },
    {
        id: '65',
        firstName: 'Tracy',
        lastName: 'Montgomery',
        name: 'Tracy Montgomery',
        role: 'Technical Writer',
        company: 'Galactic',
    },
    {
        id: '66',
        firstName: 'Barbara',
        lastName: 'Rivera',
        name: 'Barbara Rivera',
        role: 'Software Architect',
        company: 'Eureka',
    },
    {
        id: '67',
        firstName: 'William',
        lastName: 'Robbins',
        name: 'William Robbins',
        role: 'Financial Analyst',
        company: 'Luminous',
    },
    {
        id: '68',
        firstName: 'Gloria',
        lastName: 'Bishop',
        name: 'Gloria Bishop',
        role: 'Data Engineer',
        company: 'Horizon',
    },
    {
        id: '69',
        firstName: 'Julie',
        lastName: 'Edwards',
        name: 'Julie Edwards',
        role: 'Quality Assurance',
        company: 'Gates',
    },
    {
        id: '70',
        firstName: 'Daniel',
        lastName: 'Fox',
        name: 'Daniel Fox',
        role: 'System Administrator',
        company: 'Zenith',
    },
    {
        id: '71',
        firstName: 'Wendy',
        lastName: 'Black',
        name: 'Wendy Black',
        role: 'Technical Consultant',
        company: 'Netrix',
    },
    {
        id: '72',
        firstName: 'Kenneth',
        lastName: 'Mitchell',
        name: 'Kenneth Mitchell',
        role: 'UX Designer',
        company: 'Dreamweaver',
    },
    {
        id: '73',
        firstName: 'Alice',
        lastName: 'Baker',
        name: 'Alice Baker',
        role: 'Solution Architect',
        company: 'Gravity',
    },
    {
        id: '74',
        firstName: 'Jordan',
        lastName: 'Reed',
        name: 'Jordan Reed',
        role: 'Graphic Designer',
        company: 'Projector',
    },
    {
        id: '75',
        firstName: 'Christina',
        lastName: 'Stewart',
        name: 'Christina Stewart',
        role: 'Product Owner',
        company: 'Atom',
    },
    {
        id: '76',
        firstName: 'Albert',
        lastName: 'Johnson',
        name: 'Albert Johnson',
        role: 'Software Developer',
        company: 'Carbon',
    },
    {
        id: '77',
        firstName: 'Theresa',
        lastName: 'Thompson',
        name: 'Theresa Thompson',
        role: 'IT Manager',
        company: 'Bit',
    },
    {
        id: '78',
        firstName: 'Dennis',
        lastName: 'Cruz',
        name: 'Dennis Cruz',
        role: 'AI Specialist',
        company: 'Cipher',
    },
    {
        id: '79',
        firstName: 'Cheryl',
        lastName: 'Morales',
        name: 'Cheryl Morales',
        role: 'Marketing Manager',
        company: 'Fantasy',
    },
    {
        id: '80',
        firstName: 'Danielle',
        lastName: 'Perez',
        name: 'Danielle Perez',
        role: 'Data Analyst',
        company: 'Comet',
    },
    {
        id: '81',
        firstName: 'Antonio',
        lastName: 'Lucas',
        name: 'Antonio Lucas',
        role: 'Mobile Developer',
        company: 'Sparkler',
    },
    {
        id: '82',
        firstName: 'Jose',
        lastName: 'Kelley',
        name: 'Jose Kelley',
        role: 'Infrastructure Engineer',
        company: 'Protector',
    },
    {
        id: '83',
        firstName: 'Fred',
        lastName: 'Marshall',
        name: 'Fred Marshall',
        role: 'Software Tester',
        company: 'Violet',
    },
    {
        id: '84',
        firstName: 'Evelyn',
        lastName: 'Harris',
        name: 'Evelyn Harris',
        role: 'Data Warehouse Engineer',
        company: 'Nova',
    },
    {
        id: '85',
        firstName: 'Betty',
        lastName: 'Murray',
        name: 'Betty Murray',
        role: 'Full Stack Developer',
        company: 'Eden',
    },
    {
        id: '86',
        firstName: 'Shirley',
        lastName: 'Cook',
        name: 'Shirley Cook',
        role: 'Desktop Support Technician',
        company: 'Solstice',
    },
    {
        id: '87',
        firstName: 'Scott',
        lastName: 'Clarkson',
        name: 'Scott Clarkson',
        role: 'IT Support Specialist',
        company: 'Element',
    },
    {
        id: '88',
        firstName: 'Karen',
        lastName: 'Lynch',
        name: 'Karen Lynch',
        role: 'Security Analyst',
        company: 'Neon',
    },
    {
        id: '89',
        firstName: 'Patrick',
        lastName: 'Stevenson',
        name: 'Patrick Stevenson',
        role: 'Database Administrator',
        company: 'Illumination',
    },
    {
        id: '90',
        firstName: 'Katherine',
        lastName: 'Moore',
        name: 'Katherine Moore',
        role: 'Business Developer',
        company: 'Quantum',
    },
    {
        id: '91',
        firstName: 'Emily',
        lastName: 'Miller',
        name: 'Emily Miller',
        role: 'User Researcher',
        company: 'Duet',
    },
    {
        id: '92',
        firstName: 'Steven',
        lastName: 'Davis',
        name: 'Steven Davis',
        role: 'Systems Administrator',
        company: 'Homestead',
    },
    {
        id: '93',
        firstName: 'Monica',
        lastName: 'Reed',
        name: 'Monica Reed',
        role: 'Technical Trainer',
        company: 'Lantern',
    },
    {
        id: '94',
        firstName: 'Vincent',
        lastName: 'Bennett',
        name: 'Vincent Bennett',
        role: 'Security Consultant',
        company: 'Aurora',
    },
    {
        id: '95',
        firstName: 'Steven',
        lastName: 'Medina',
        name: 'Steven Medina',
        role: 'Software Consultant',
        company: 'Meteor',
    },
    {
        id: '96',
        firstName: 'Deborah',
        lastName: 'Bell',
        name: 'Deborah Bell',
        role: 'Product Designer',
        company: 'Time',
    },
    {
        id: '97',
        firstName: 'Willie',
        lastName: 'Wood',
        name: 'Willie Wood',
        role: 'Business Systems Analyst',
        company: 'Trailblazer',
    },
    {
        id: '98',
        firstName: 'Catherine',
        lastName: 'Howard',
        name: 'Catherine Howard',
        role: 'Technical Product Manager',
        company: 'Glacier',
    },
    {
        id: '99',
        firstName: 'Aaron',
        lastName: 'Adams',
        name: 'Aaron Adams',
        role: 'Systems Engineer',
        company: 'Venom',
    },
    {
        id: '100',
        firstName: 'Edward',
        lastName: 'Garcia',
        name: 'Edward Garcia',
        role: 'Software Architect',
        company: 'Eclipse',
    },
    {
        id: '101',
        firstName: 'Lisa',
        lastName: 'Johnson',
        name: 'Lisa Johnson',
        role: 'Engineer',
        company: 'SeaCo',
    },
    {
        id: '102',
        firstName: 'Mike',
        lastName: 'Williams',
        name: 'Mike Williams',
        role: 'Data Scientist',
        company: 'PHJ',
    },
    {
        id: '103',
        firstName: 'Mary',
        lastName: 'Jones',
        name: 'Mary Jones',
        role: 'Software Architect',
        company: 'MyCo',
    },
    {
        id: '104',
        firstName: 'Chris',
        lastName: 'Miller',
        name: 'Chris Miller',
        role: 'QA Engineer',
        company: 'Zen',
    }]


export const commendedByContacts = [
    {
        id: '201',
        firstName: 'Alex',
        lastName: 'Davis',
        name: 'Alex Davis',
        role: 'Software Engineer',
        company: 'Google',
    },
    {
        id: '202',
        firstName: 'Sarah',
        lastName: 'Williams',
        name: 'Sarah Williams',
        role: 'Software Engineer',
        company: 'Google',
    },
    {
        id: '203',
        firstName: 'Mark',
        lastName: 'Taylor',
        name: 'Mark Taylor',
        role: 'Software Engineer',
        company: 'Google',
    },
    {
        id: '204',
        firstName: 'Elizabeth',
        lastName: 'Davis',
        name: 'Elizabeth Davis',
        role: 'Software Engineer',
        company: 'Google',
    },
    {
        id: '205',
        firstName: 'Adriano',
        lastName: 'Basso',
        name: 'Adriano Basso',
        role: 'Product Manager',
        company: 'Hazy',
    }]

export const commendedContacts = [{name: 'John Doe', id: 1}, {name: 'Jane Doe', id:2}]